"""empty message

Revision ID: 174c483857ba
Revises: 6b61a28f250b
Create Date: 2022-08-31 13:48:15.016358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174c483857ba'
down_revision = '6b61a28f250b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
