"""empty message

Revision ID: 2fd4fa3a2016
Revises: 174c483857ba
Create Date: 2022-08-31 13:48:39.569318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd4fa3a2016'
down_revision = '174c483857ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
