"""empty message

Revision ID: 42151183038e
Revises: ee436d22e43b
Create Date: 2022-08-31 13:51:16.762034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42151183038e'
down_revision = 'ee436d22e43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
