"""empty message

Revision ID: 60136e2e733c
Revises: 2fd4fa3a2016
Create Date: 2022-08-31 13:49:06.699164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60136e2e733c'
down_revision = '2fd4fa3a2016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
