"""empty message

Revision ID: 67bfd64b28bd
Revises: 9e3b85da60fb
Create Date: 2022-08-31 13:52:34.225139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bfd64b28bd'
down_revision = '9e3b85da60fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
