"""empty message

Revision ID: 6b61a28f250b
Revises: 75641bce0390
Create Date: 2022-08-31 13:47:16.654848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b61a28f250b'
down_revision = '75641bce0390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
