"""empty message

Revision ID: 866bab0daad7
Revises: 67bfd64b28bd
Create Date: 2022-08-31 13:57:42.750049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866bab0daad7'
down_revision = '67bfd64b28bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
