"""empty message

Revision ID: 9e3b85da60fb
Revises: 42151183038e
Create Date: 2022-08-31 13:52:09.801409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3b85da60fb'
down_revision = '42151183038e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'city')
    # ### end Alembic commands ###
