"""empty message

Revision ID: dd888fccb057
Revises: 60136e2e733c
Create Date: 2022-08-31 13:49:57.243795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd888fccb057'
down_revision = '60136e2e733c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
