"""empty message

Revision ID: ee436d22e43b
Revises: dd888fccb057
Create Date: 2022-08-31 13:50:26.578750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee436d22e43b'
down_revision = 'dd888fccb057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
